# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import Qt, QRect, QMetaObject, QCoreApplication
from PyQt5.QtGui import QIcon, QPixmap
from PyQt5.QtWidgets import QWidget, QVBoxLayout, QTabWidget, QHBoxLayout, QMenuBar, QStatusBar, QToolBar, QAction

# from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.resize(618, 339)
        MainWindow.setContextMenuPolicy(Qt.DefaultContextMenu)
        MainWindow.setStyleSheet("QToolTip {\n"
"    border: 2px solid darkkhaki;\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"    opacity: 200;\n"
"}")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # --------------------------
        # self.table = Table()
        # self.tabWidget.addTab(self.table, "Tabla Nueva")
        # --------------------------

        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(QRect(0, 0, 618, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setStyleSheet("QToolBar{\n"
"    spacing:14px;\n"
"}")
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QAction(MainWindow)
        icon = QIcon()
        icon.addPixmap(QPixmap(":/new/img/new.png"), QIcon.Normal, QIcon.Off)
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QAction(MainWindow)
        icon1 = QIcon()
        icon1.addPixmap(QPixmap(":/import/img/import.png"), QIcon.Normal, QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QAction(MainWindow)
        icon2 = QIcon()
        icon2.addPixmap(QPixmap(":/save/img/save.png"), QIcon.Normal, QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionPaste = QAction(MainWindow)
        icon3 = QIcon()
        icon3.addPixmap(QPixmap(":/paste/img/paste.png"), QIcon.Normal, QIcon.Off)
        self.actionPaste.setIcon(icon3)
        self.actionPaste.setObjectName("actionPaste")
        self.actionCopy = QAction(MainWindow)
        icon4 = QIcon()
        icon4.addPixmap(QPixmap(":/copy/img/copy.png"), QIcon.Normal, QIcon.Off)
        self.actionCopy.setIcon(icon4)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPrint = QAction(MainWindow)
        icon5 = QIcon()
        icon5.addPixmap(QPixmap(":/print/img/print.png"), QIcon.Normal, QIcon.Off)
        self.actionPrint.setIcon(icon5)
        self.actionPrint.setObjectName("actionPrint")

        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionPrint)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Visor CSV"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setToolTip(_translate("MainWindow",
                                             "<html><head/><body><p><span style=\" font-weight:600;\">Nuevo Fichero</span></p></body></html>"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setToolTip(_translate("MainWindow",
                                              "<html><head/><body><p><span style=\" font-weight:600;\">Abrir fichero</span></p></body></html>"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow",
                                              "<html><head/><body><p><span style=\" font-weight:600;\">Guardar</span></p></body></html>"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setToolTip(_translate("MainWindow",
                                               "<html><head/><body><p><span style=\" font-weight:600;\">pegar texto</span></p></body></html>"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setToolTip(_translate("MainWindow",
                                              "<html><head/><body><p><span style=\" font-weight:600;\">copiar texto</span></p></body></html>"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionPrint.setToolTip(_translate("MainWindow",
                                               "<html><head/><body><p><span style=\" font-weight:600;\">imprimir documento actual</span></p></body></html>"))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P"))
import resource_rc
